local s,id=GetID()
function s.initial_effect(c)
	local g=Group.CreateGroup()
	g:KeepAlive()
	--Activate
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	c:RegisterEffect(e1)
	--
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD)
	e2:SetCode(EFFECT_HAND_LIMIT)
	e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e2:SetRange(LOCATION_SZONE)
	e2:SetTargetRange(1,0)
	e2:SetValue(100)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e3:SetProperty(EFFECT_FLAG_DELAY)
	e3:SetRange(LOCATION_SZONE)
	e3:SetCode(EVENT_TO_HAND)
	e3:SetLabelObject(g)
	e3:SetOperation(s.recop)
	c:RegisterEffect(e3)
	local e4=e3:Clone()
	e4:SetCode(EVENT_TO_GRAVE)
	c:RegisterEffect(e4)
	local e5=e3:Clone()
	e5:SetCode(EVENT_REMOVE)
	c:RegisterEffect(e5)
	local e6=e3:Clone()
	e6:SetCode(EVENT_SPSUMMON_SUCCESS)
	c:RegisterEffect(e6)
	local e7=e3:Clone()
	e7:SetCode(EVENT_SSET)
	c:RegisterEffect(e7)
	local e8=Effect.CreateEffect(c)
	e8:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e8:SetCode(EVENT_PHASE+PHASE_END)
	e8:SetRange(LOCATION_SZONE)
	e8:SetCountLimit(1)
	e8:SetLabelObject(g)
	e8:SetOperation(s.activate)
	c:RegisterEffect(e8)
end
function s.filter(c,e,tp)
	return c:IsPreviousLocation(LOCATION_DECK) and c:IsPreviousControler(tp) and c:IsControler(tp)
end
function s.recop(e,tp,eg,ep,ev,re,r,rp)
	local token=nil
	local g=eg:Filter(s.filter,nil,e,tp)
	for tc in aux.Next(g) do
		token=Duel.CreateToken(tp,tc:GetOriginalCode())
		e:GetLabelObject():AddCard(token)
	end
end
function s.activate(e,tp,eg,ep,ev,re,r,rp)
	Duel.SendtoDeck(e:GetLabelObject(),nil,SEQ_DECKBOTTOM,REASON_EFFECT)
	e:GetLabelObject():Clear()
end