function c100001193.initial_effect(c)
	c:EnableReviveLimit()
		--special summon
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_SPSUMMON_PROC)
	e1:SetProperty(EFFECT_FLAG_SPSUM_PARAM+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_EXTRA)
		e1:SetTargetRange(POS_FACEUP_ATTACK,0)
	e1:SetCondition(c100001193.spcon)
	e1:SetValue(1)
	c:RegisterEffect(e1)
	--spsummon condition
	local e2=Effect.CreateEffect(c)
	e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetCode(EFFECT_SPSUMMON_CONDITION)
	c:RegisterEffect(e2)
	--spsummon
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_SINGLE)
	e4:SetCode(EFFECT_CANNOT_DISABLE_SPSUMMON)
	e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	c:RegisterEffect(e4)
		--cannot release
	local e11=Effect.CreateEffect(c)
	e11:SetType(EFFECT_TYPE_SINGLE)
	e11:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e11:SetRange(LOCATION_MZONE)
	e11:SetCode(EFFECT_UNRELEASABLE_SUM)
	e11:SetValue(1)
	c:RegisterEffect(e11)
	local e12=e11:Clone()
	e12:SetCode(EFFECT_UNRELEASABLE_NONSUM)
	c:RegisterEffect(e12)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e3:SetCode(EFFECT_CANNOT_BE_FUSION_MATERIAL)
	e3:SetValue(1)
	c:RegisterEffect(e3)
	local e4=e3:Clone()
	e4:SetCode(EFFECT_CANNOT_BE_SYNCHRO_MATERIAL)
	c:RegisterEffect(e4)
	local e5=e3:Clone()
	e5:SetCode(EFFECT_CANNOT_BE_XYZ_MATERIAL)
	c:RegisterEffect(e5)
		--attack limit
	local e6=Effect.CreateEffect(c)
	e6:SetType(EFFECT_TYPE_SINGLE)
	e6:SetCode(EFFECT_CANNOT_ATTACK)
	c:RegisterEffect(e6)
	--cannot be target
	local e7=Effect.CreateEffect(c)
	e7:SetType(EFFECT_TYPE_SINGLE)
	e7:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e7:SetCode(EFFECT_IGNORE_BATTLE_TARGET)
	e7:SetRange(LOCATION_MZONE)
	e7:SetValue(aux.imval1)
	c:RegisterEffect(e7)
		--cannot link material
	local e10=Effect.CreateEffect(c)
	e10:SetType(EFFECT_TYPE_SINGLE)
	e10:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e10:SetCode(EFFECT_CANNOT_BE_LINK_MATERIAL)
	e10:SetValue(1)
	c:RegisterEffect(e10)
		--return
		local e22=Effect.CreateEffect(c)
	e22:SetDescription(aux.Stringid(100000853,0))
	e22:SetCategory(CATEGORY_TODECK)
	e22:SetType(EFFECT_TYPE_IGNITION)
	e22:SetRange(LOCATION_GRAVE+LOCATION_REMOVED+LOCATION_ONFIELD)
	e22:SetTarget(c100001193.tg)
	e22:SetOperation(c100001193.op)
	c:RegisterEffect(e22)
		--immune
	local e15=Effect.CreateEffect(c)
	e15:SetType(EFFECT_TYPE_SINGLE)
	e15:SetCode(EFFECT_IMMUNE_EFFECT)
	e15:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e15:SetRange(LOCATION_EXTRA+LOCATION_GRAVE+LOCATION_REMOVED+LOCATION_ONFIELD)
	e15:SetValue(c100001193.efilter)
	c:RegisterEffect(e15)
			--splimit
	local e21=Effect.CreateEffect(c)
	e21:SetType(EFFECT_TYPE_FIELD)
	e21:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
	e21:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_CANNOT_NEGATE)
	e21:SetRange(LOCATION_MZONE)
	e21:SetTargetRange(1,0)
	e21:SetTarget(c100001193.splimit)
	c:RegisterEffect(e21)
end
function c100001193.splimit(e,c)
	return c:IsLocation(LOCATION_EXTRA) and not (c:IsSetCard(0x750) or c:IsSetCard(0x751) or c:IsSetCard(0x752) or c:IsSetCard(0x753) or c:IsSetCard(0x754) or c:IsSetCard(0x755) or c:IsSetCard(0x756) or c:IsSetCard(0x757) or c:IsSetCard(0x758) or c:IsSetCard(0x759) or c:IsSetCard(0x75A) or c:IsSetCard(0x75B) or c:IsSetCard(0x75C) or c:IsSetCard(0x75D) or c:IsSetCard(0x75E) or c:IsSetCard(0x75F) or c:IsSetCard(0x760) or c:IsSetCard(0x761) or c:IsSetCard(0x762) or c:IsSetCard(0x763) or c:IsSetCard(0x764) or c:IsSetCard(0x765) or c:IsSetCard(0x766) or c:IsSetCard(0x767) or c:IsSetCard(0x768) or c:IsCode(100000921) or c:IsCode(100000993) or c:IsCode(100000978) or c:IsCode(100001184) or c:IsCode(100001193) or c:IsCode(100000970) or c:IsCode(100000971))
end
function c100001193.efilter(e,te)
	return te:GetOwner()~=e:GetOwner()
end
function c100001193.tg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return e:GetHandler():IsAbleToExtra() end
	Duel.SetOperationInfo(0,CATEGORY_TODECK,e:GetHandler(),1,0,0)
	Duel.SetChainLimit(aux.FALSE)
end
function c100001193.op(e,tp,eg,ep,ev,re,r,rp)
	if not e:GetHandler():IsRelateToEffect(e) then return end
	Duel.SendtoDeck(e:GetHandler(),nil,2,REASON_EFFECT)
end
function c100001193.spcon(e,c)
	if c==nil then return true end
	return Duel.GetLocationCount(c:GetControler(),LOCATION_MZONE)>-1
end
